# name: project-onyx

# on:
#   push:
#     branches:
#       - main

# jobs:
#   runs-tests:
#     name: runs-tests
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.12'

#       - name: Install dependencies
#         run: make requirements

#       - name: Set up dev
#         run: make dev-setup

#       - name: Run tests
#         run: make run-checks

#   deploy-lambda:
#     name: deploy-lambda
#     needs: runs-tests
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ${{ secrets.AWS_REGION }}

#       - name: Terraform Init
#         working-directory: terraform
#         run: terraform init

#       - name: Terraform Plan
#         working-directory: terraform     
#         run: terraform plan

#       - name: Terraform Apply
#         working-directory: terraform
#         run: terraform apply -auto-approve
